Tamanhos:
    Terrenos:
       Pequeno: 12
       Medio: 22
       Grande: 30
    DistanciaMinima: 1
Valores:
    Terreno:
        Pequeno: 50000.0
        Medio: 150000.0
        Grande: 2000000.0
    Funcao:
        AtivarPVP: 50000.0
        DesativarPVP: 250000.0
        AtivarEntrada: 50000.0
        AtivarCMD: 50000.0
        DesativarCMD: 200000.0
        DesativarEntrada: 500000.0
        DesativarFix: 500000.0
        AtivarFix: 50000.0
Outros:
    CriarCerca: true
    IDCerca: 113
    MundosBloqueados:
     - endcraft
     - endcraft_the_end
     - SpotWorld
     - plotworld
    Multiplicador:
        world_teste:
           Valor: 2
    Schematics:
        world_teste:
           Pequeno:
               SchemName: teste
default-lang: pt_br